### ISSUE TITLE
Format Error on Website

### ISSUE THREAD

**Issue by mkwlf** [spryker/documentation#153]
on the [Core Extension](https://documentation.spryker.com/v4/docs/core-extension) page and [Extending the Spryker-Core Functionality](https://documentation.spryker.com/v4/docs/t-extend-spryker)

the backtick `` ` `` code segments are not wrapped in `<code>`. 

They are represented fine in github:
![image](https://user-images.githubusercontent.com/2796409/88371967-58b06d80-cd95-11ea-8f44-fb24fe7baf14.png)

But not on spryker doc page:
![image](https://user-images.githubusercontent.com/2796409/88372113-990feb80-cd95-11ea-87b9-4c71d2d69564.png)

**Comment by lenadoc** [comment]
Hi Mike,

Thank you very much for reporting the issue. It has now been fixed. 
You further contribution would be greatly appreciated!

Best regards,
The Spryker Documentation team
