### ISSUE TITLE
while building and installing demo spryker B2C, 'docker-sync' is not found. 

### ISSUE THREAD

**Issue by ed42311** [spryker/documentation#224]
### at this step

![Screen Shot 2021-01-06 at 4 58 09 PM](https://user-images.githubusercontent.com/14878694/103834413-9140bc80-5040-11eb-874d-c367917a6f44.png)

### with these versions

![Screen Shot 2021-01-06 at 5 06 03 PM](https://user-images.githubusercontent.com/14878694/103834747-83d80200-5041-11eb-9cf3-93e812f30db4.png)

### Ran into this error

```
Running generator
'docker-sync' is not found. Please, make sure this application is installed and added to PATH.
```

### Solved with this

```
❯
❯ sudo gem install docker-sync
```

found here:  https://docker-sync.readthedocs.io/en/latest/advanced/sync-strategies.html

**Comment by tvaleriy** [comment]
Hi @ed42311,
thank you for the report. Indeed our documentation is kind of "newer" than our actual code base here. Installation guide says to use mutagen but code base is still using docker-sync for syncing purposes.
We are currently deciding on what should we fix. I'll keep you updated about the result.

Best,
Spryker Support Team
